[pytest]
DJANGO_SETTINGS_MODULE = fkapi.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --reuse-db --nomigrations
testpaths = fkapi
norecursedirs = .* venv .venv
pythonpath = .
