"""
Django settings for fkapi project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
from pathlib import Path

from dotenv import load_dotenv

try:
    from celery.schedules import crontab

    CELERY_AVAILABLE = True
except ImportError:
    CELERY_AVAILABLE = False
    crontab = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment with validation
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "insecure-dev-key-only-for-development"
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set in production")

# Load allowed hosts from env (comma-separated). Fall back to localhost and optional PROJECT_IP.
_allowed_hosts_env = os.getenv("DJANGO_ALLOWED_HOSTS")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    default_ip = os.environ.get("PROJECT_IP")
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"] + ([default_ip] if default_ip else [])

ENABLE_CELERY = os.getenv("ENABLE_CELERY", "True" if CELERY_AVAILABLE else "False").lower() in ("1", "true", "yes")

if ENABLE_CELERY and CELERY_AVAILABLE:
    CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379")
    CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379")
    CELERY_BEAT_SCHEDULE = {
        "scrape_daily": {
            "task": "core.tasks.scrape_daily",
            "schedule": crontab(hour=0, minute=0),
        },
    }
else:
    CELERY_BROKER_URL = None
    CELERY_RESULT_BACKEND = None
    CELERY_BEAT_SCHEDULE = {}

# Cache configuration
# Use Redis if available, fallback to local memory
# If Celery is enabled, prefer Redis for cache to share between processes
USE_REDIS_CACHE = os.getenv("USE_REDIS_CACHE", "False").lower() in ("1", "true", "yes")

# If Celery is enabled, try to use Redis for cache (needed for worker-server communication)
if ENABLE_CELERY and CELERY_AVAILABLE and not USE_REDIS_CACHE:
    try:
        import redis
        r = redis.Redis(host='localhost', port=6379, db=1, socket_connect_timeout=1)
        r.ping()
        USE_REDIS_CACHE = True
        logger = logging.getLogger(__name__)
        logger.info("Celery detected: Auto-enabling Redis cache for inter-process communication")
    except Exception:
        pass

if USE_REDIS_CACHE:
    REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/1")
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,  # Fallback to no-op if Redis unavailable
            },
            "KEY_PREFIX": "fkapi",
            "TIMEOUT": 3600,
        }
    }
else:
    # Use local memory cache (no Redis needed)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "KEY_PREFIX": "fkapi",
            "TIMEOUT": 3600,
        }
    }

# Cache settings
CACHE_TIMEOUT_SHORT = 300  # 5 minutes
CACHE_TIMEOUT_MEDIUM = 1800  # 30 minutes
CACHE_TIMEOUT_LONG = 3600  # 1 hour
CACHE_TIMEOUT_VERY_LONG = 86400  # 24 hours

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    #'django.contrib.sites',
    "ninja",
    "ninja_apikey",
    "core",
    "colorfield",
    "django_countries",
]

if ENABLE_CELERY and CELERY_AVAILABLE:
    INSTALLED_APPS += ["celery", "django_celery_beat"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.rate_limit_middleware",
    "core.middleware.performance_monitoring_middleware",
]

ROOT_URLCONF = "fkapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fkapi.wsgi.application"


load_dotenv()


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT") or "5432",
        "CONN_MAX_AGE": 60,
        "OPTIONS": {
            "keepalives": 1,
            "keepalives_idle": 30,
            "keepalives_interval": 10,
            "keepalives_count": 5,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Performance Monitoring Settings
SLOW_QUERY_THRESHOLD = float(os.getenv("SLOW_QUERY_THRESHOLD", "0.5"))
SLOW_RESPONSE_THRESHOLD = float(os.getenv("SLOW_RESPONSE_THRESHOLD", "1.0"))
LOG_DB_QUERIES = os.getenv("LOG_DB_QUERIES", "False").lower() in ("1", "true", "yes")

# API Rate Limit Whitelist
_api_rate_limit_whitelist_env = os.getenv("API_RATE_LIMIT_WHITELIST", "")
if _api_rate_limit_whitelist_env:
    API_RATE_LIMIT_WHITELIST = [ip.strip() for ip in _api_rate_limit_whitelist_env.split(",") if ip.strip()]
else:
    API_RATE_LIMIT_WHITELIST = []

# Logging Configuration
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "performance.log",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "performance": {
            "handlers": ["console", "file"] if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"] if LOG_DB_QUERIES else [],
            "level": "INFO" if LOG_DB_QUERIES else "WARNING",
            "propagate": False,
        },
    },
}

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = "DENY"
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    X_FRAME_OPTIONS = "SAMEORIGIN"

# Django Debug Toolbar (only in development)
if DEBUG:
    try:
        import debug_toolbar  # noqa: F401, PLC0415

        INSTALLED_APPS += ["debug_toolbar"]
        MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
        INTERNAL_IPS = ["127.0.0.1", "localhost"]
    except ImportError:
        pass
