# Generated by Django 5.0.4 on 2026-01-19 08:28

import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


def seed_initial_colors(apps, schema_editor):
    """
    Seed a basic palette of colors matching the naming used on Football Kit Archive.

    These names are the human-readable labels that appear on the web
    (e.g. "Off-white / Claret"), so that lookups by name in the scraper
    match exactly one Color instance.
    """
    Color = apps.get_model("core", "Color")

    initial_colors = [
        ("White", "#FFFFFF"),
        ("Red", "#FF0000"),
        ("Blue", "#0000FF"),
        ("Black", "#000000"),
        ("Yellow", "#FFFF00"),
        ("Green", "#008000"),
        ("Sky blue", "#87CEEB"),
        ("Navy", "#000080"),
        ("Orange", "#FFA500"),
        ("Gray", "#808080"),
        ("Claret", "#7F1734"),
        ("Purple", "#800080"),
        ("Pink", "#FFC0CB"),
        ("Brown", "#964B00"),
        ("Gold", "#BFAB40"),
        ("Silver", "#C0C0C0"),
        ("Off-white", "#F5F5F5"),
    ]

    for name, hex_code in initial_colors:
        Color.objects.get_or_create(
            name=name,
            defaults={"color": hex_code},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
                ('first_year', models.CharField(max_length=4)),
                ('second_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_dark', models.URLField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_brand_name_92371f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fka', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores, hyphens, or Romanian characters.", regex='^[-a-zA-Z0-9_ăâîșțĂÂÎȘȚ]+$')])),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_dark', models.URLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_club_name_fb94dc_idx'), models.Index(fields=['country'], name='core_club_country_52b020_idx')],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_dark', models.URLField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_compet_name_fdab63_idx'), models.Index(fields=['country'], name='core_compet_country_9e10ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('color_r', models.IntegerField(default=0)),
                ('color_g', models.IntegerField(default=0)),
                ('color_b', models.IntegerField(default=0)),
                ('parent_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.color')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores, hyphens, or Romanian characters.", regex='^[-a-zA-Z0-9_ăâîșțĂÂÎȘȚ]+$')])),
                ('kit_id', models.CharField(blank=True, help_text='ID from FootballKitArchive for URL construction', max_length=20, null=True)),
                ('main_img_url', models.URLField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fh_link', models.URLField(blank=True, null=True)),
                ('web_updated', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('design', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('competition', models.ManyToManyField(to='core.competition')),
                ('primary_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_color', to='core.color')),
                ('secondary_color', models.ManyToManyField(blank=True, related_name='secondary_color', to='core.color')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type_k')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_kit_name_3eb483_idx'), models.Index(fields=['team', 'season'], name='core_kit_team_id_9eebfc_idx'), models.Index(fields=['main_img_url'], name='core_kit_main_im_8c0fb8_idx'), models.Index(fields=['web_updated'], name='core_kit_web_upd_ea3d44_idx'), models.Index(fields=['last_updated'], name='core_kit_last_up_08eed5_idx'), models.Index(fields=['rating'], name='core_kit_rating_e7d577_idx')],
            },
        ),
        migrations.RunPython(seed_initial_colors, migrations.RunPython.noop),
    ]
