# Generated by Django 5.0.4 on 2024-04-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_color_kit_competition_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_color', to='core.variation'),
        ),
        migrations.AddField(
            model_name='kit',
            name='secondary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_color', to='core.variation'),
        ),
    ]
