# Generated by Django 5.0.4 on 2024-04-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kit_primary_color_kit_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type_k'),
        ),
    ]
