# Generated by Django 5.0.4 on 2024-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_kit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='color_g',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='color_r',
            field=models.IntegerField(default=0),
        ),
    ]
