# Generated by Django 5.0.4 on 2024-04-29 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variation_color_b_variation_color_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_color', to='core.variation'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='secondary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_color', to='core.variation'),
        ),
    ]
