# Generated by Django 5.0.4 on 2024-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_kit_primary_color_alter_kit_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='web_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
