# Generated by Django 5.0.4 on 2024-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_brand_slug_alter_club_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
