# Generated by Django 5.0.4 on 2024-05-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_brand_slug_alter_competition_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
