# Generated by Django 5.0.4 on 2024-05-19 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_kit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores, hyphens, or Romanian characters.", regex='^[-a-zA-Z0-9_ăâîșțĂÂÎȘȚ]+$')]),
        ),
        migrations.AlterField(
            model_name='kit',
            name='slug',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message="Enter a valid 'slug' consisting of letters, numbers, underscores, hyphens, or Romanian characters.", regex='^[-a-zA-Z0-9_ăâîșțĂÂÎȘȚ]+$')]),
        ),
    ]
